### ISSUE TITLE
Please re run the results! 

### ISSUE THREAD

**Issue by LifeIsStrange** [oprogramador/github-languages#5]
P l e a s e

**Comment by oprogramador** [comment]
@LifeIsStrange 

I was planning to rerun in the next year but if you want, I can update when I find some time.

**Comment by LifeIsStrange** [comment]
Haha whenever you want!
BTW I believe github octoverse 2019 will soon be published!

**Comment by oprogramador** [comment]
I just updated README according to the newest results.
An example difference is that in the previous run (February this year) Swift was among the top growing languages but now Swift isn't present among them while Dart is.

**Comment by LifeIsStrange** [comment]
@oprogramador
THANKS :)
